### ISSUE TITLE
Need to prefix original macros from nette

### ISSUE THREAD

**Issue by martinknor** [instante/extended-form-macros#1]
Because it broke other components which use nette inputs.

```
label, input, input.errors
```

**Comment by richard-ejem** [comment]
These overrides are designed to be compatible with original macros, they should just extend their capabilities. If they aren't, it would be nice to fix the incompatibility :)

Or, if you are facing some rare edge case (no one requested such feature yet), you can simply register original Nette macros with prefixed names in your code. I don't want this library to automatically register original versions of these macros while most users don't want nor need it.

I don't know what issue exactly do you face, so I'm not able assess the best solution.

**Comment by martinknor** [comment]
Problem was that form wasn't wrapped by snippetArea. Solved.
